Repository boostorg/gil, pull requests merged in 2018-03, with the labels that each got.

#53 Add GitHub templates for issue and pull request
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#56 First stab at README
  README.md
Labels: documentation

#59 generate indexed_image_view
  include/boost/gil/extension/toolbox/image_types/indexed_image.hpp
  toolbox/test/indexed_image_test.cpp
Labels: toolbox

#68 Fixes of potential UB due to overflowing bit-shift operation
  include/boost/gil/channel_algorithm.hpp
  include/boost/gil/extension/io/formats/bmp/reader_backend.hpp
  include/boost/gil/extension/io/formats/bmp/scanline_read.hpp
  include/boost/gil/extension/io/formats/bmp/write.hpp
  include/boost/gil/extension/io/formats/png/writer_backend.hpp
Labels: bug
