Repository boostorg/gil, pull requests merged in 2019-10, with the labels that each got.

#393 Implemented median_filter
  include/boost/gil/image_processing/filter.hpp
  test/core/image_processing/CMakeLists.txt
  test/core/image_processing/Jamfile
  test/core/image_processing/median_filter.cpp
Labels: cat/feature

#397 Hide convolve_1d, convolve_2d and kernel_2 in namespace detail
  example/convolve2d.cpp
  include/boost/gil/extension/numeric/convolve.hpp
  include/boost/gil/extension/numeric/kernel.hpp
  include/boost/gil/image_processing/filter.hpp
  include/boost/gil/image_processing/threshold.hpp
  test/extension/numeric/convolve.cpp
  test/extension/numeric/convolve_2d.cpp
  test/extension/numeric/kernel.cpp
Labels: cat/refactoring, ext/numeric

#398 Update extend_boundary function to handle all boundary_option-s
  include/boost/gil/extension/numeric/algorithm.hpp
  test/extension/numeric/extend_boundary.cpp
Labels: cat/enhancement

#399 Fix void istream_device::read function returning a value
  include/boost/gil/io/device.hpp
Labels: cat/bug, core/io

#400 Flatten structure of test/extension/io/output/ folder
  test/extension/io/.gitignore
  test/extension/io/images/jpeg/EddDawson/36dpi.jpg
  test/extension/io/images/jpeg/test.jpg
  test/extension/io/output/.keep
  test/extension/io/paths.hpp
Labels: cat/annoyance, ext/io

#392 Implement Sobel and Scharr operators
  .gitignore
  example/Jamfile
  example/harris.cpp
  example/hessian.cpp
  example/sobel_scharr.cpp
  include/boost/gil/detail/math.hpp
  include/boost/gil/image_processing/harris.hpp
  include/boost/gil/image_processing/hessian.hpp
  include/boost/gil/image_processing/numeric.hpp
  include/boost/gil/image_processing/threshold.hpp
  test/core/image_processing/CMakeLists.txt
  test/core/image_processing/Jamfile
  test/core/image_processing/harris.cpp
  test/core/image_processing/hessian.cpp
  test/core/image_processing/simple_kernels.cpp
  test/core/image_processing/sobel_scharr.cpp
Labels: cat/feature
