Repository boostorg/gil, pull requests merged in 2019-08, with the labels that each got.

#361 Added 2D kernel definitions to numeric extension
  include/boost/gil/extension/numeric/kernel.hpp
  test/extension/numeric/kernel.cpp
Labels: cat/feature, status/work-in-progress

#365 Split pixel_types fixture to integer and float pixel types
  test/core/pixel/test_fixture.hpp
Labels: cat/refactoring, test

#125 Add test for three color types of PNG with tRNS chunk
  test/extension/io/Jamfile
  test/extension/io/images/png/PngSuite/tbbn0g04.png
  test/extension/io/images/png/PngSuite/tbbn2c16.png
  test/extension/io/images/png/PngSuite/tbbn3p08.png
  test/extension/io/images/png/PngSuite/tbgn2c16.png
  test/extension/io/images/png/PngSuite/tbgn3p08.png
  test/extension/io/images/png/PngSuite/tbrn2c08.png
  test/extension/io/images/png/PngSuite/tbwn0g16.png
  test/extension/io/images/png/PngSuite/tm3n3p02.png
  test/extension/io/images/png/PngSuite/tp1n3p08.png
  test/extension/io/images/png/grayalpha-with-tRNS-chunk.png
  test/extension/io/images/png/grayscale-with-tRNS-chunk.png
  test/extension/io/png_read_test.cpp
Labels: ext/io, test

#372 Add tests for extension/numeric/pixel_numeric_operations.hpp
  include/boost/gil/extension/numeric/pixel_numeric_operations.hpp
  test/extension/numeric/CMakeLists.txt
  test/extension/numeric/Jamfile
  test/extension/numeric/pixel_numeric_operations.cpp
Labels: ext/numeric, test

#367 Added 2D convolution definitions to numeric extension
  example/convolve2d.cpp
  include/boost/gil/extension/numeric/convolve.hpp
  include/boost/gil/image_processing/threshold.hpp
  test/extension/numeric/CMakeLists.txt
  test/extension/numeric/Jamfile
  test/extension/numeric/convolve.cpp
  test/extension/numeric/convolve_2d.cpp
Labels: cat/feature

#369 Replaced asserts by exceptions in low-level file I/O code
  include/boost/gil/io/device.hpp
Labels: cat/bug

#370 Mark all non-simple build targets of extension/io as explicit
  test/extension/io/Jamfile
Labels: cat/annoyance, ext/io

#378 Fix Boost guidelines violations
  include/boost/gil/extension/numeric/convolve.hpp
  include/boost/gil/extension/numeric/kernel.hpp
  include/boost/gil/image_processing/threshold.hpp
  test/extension/numeric/kernel.cpp
Labels: cat/bug, core, ext/numeric

#379 Added definition of gaussian adaptive threshold
  example/adaptive_threshold.cpp
  example/test_adaptive.png
  include/boost/gil/image_processing/threshold.hpp
Labels: cat/feature

#350 Harris response computation
  example/Jamfile
  example/harris.cpp
  include/boost/gil/image_processing/harris.hpp
  include/boost/gil/image_processing/numeric.hpp
  test/core/image_processing/CMakeLists.txt
  test/core/image_processing/Jamfile
  test/core/image_processing/harris.cpp
Labels: cat/feature

#364 Hessian corner detector
  example/hessian.cpp
  include/boost/gil/image_processing/hessian.hpp
  include/boost/gil/image_processing/numeric.hpp
  test/core/image_processing/CMakeLists.txt
  test/core/image_processing/Jamfile
  test/core/image_processing/hessian.cpp
Labels: cat/feature

#383 Add implementatin of box filter and blur
  include/boost/gil/image_processing/filter.hpp
  test/core/image_processing/CMakeLists.txt
  test/core/image_processing/Jamfile
  test/core/image_processing/box_filter.cpp
Labels: cat/feature

#385 Fixed a crash when reading PNG files with an invalid header.
  include/boost/gil/extension/io/png/detail/base.hpp
Labels: cat/annoyance, ext/io
