Repository boostorg/gil, pull requests merged in 2019-05, with the labels that each got.

#298 Add SFINAE-friendly version of std::common_type
  include/boost/gil/detail/std_common_type.hpp
  include/boost/gil/point.hpp
Labels: cat/bug

#299 Add missing equal sign in interleaved_ptr.hpp
  .gitignore
  example/interleaved_ptr.hpp
Labels: cat/bug

#293 [numeric] Add unit test for matrix3x2<T> class
  numeric/test/CMakeLists.txt
  numeric/test/Jamfile
  numeric/test/matrix3x2.cpp
  numeric/test/numeric.cpp
Labels: cat/enhancement, ext/numeric

#301 Remove unused Quickbook and HTML files
  .azure-pipelines.yml
  io/doc/Jamfile
  io/doc/html/gil/io/running_gil__io_tests.html
  io/doc/html/gil/io/tutorial.html
  io/doc/html/gil/io/using_io.html
  io/doc/html/index.html
  io/doc/io.qbk
  numeric/doc/Jamfile
  numeric/doc/numeric.qbk
  toolbox/doc/Jamfile
  toolbox/doc/toolbox.qbk
Labels: cat/documentation

#303 Define WIN32 macro to make LibRaw happy
  include/boost/gil/extension/io/raw/tags.hpp
Labels: cat/annoyance, ext/io
