Repository boostorg/gil, pull requests merged in 2019-07, with the labels that each got.

#319 Add basic test for color base algorithm: static_transform
  test/core/color_base/CMakeLists.txt
  test/core/color_base/Jamfile
  test/core/color_base/static_transform.cpp
  test/core/color_base/static_transform_gray_to_rgb_fail.cpp
  test/core/color_base/static_transform_rgb_to_cmyk_fail.cpp
Labels: core, test

#320 [numeric] std::extent not usable to obtain size of kernel_1d_fixed
  include/boost/gil/extension/numeric/convolve.hpp
  include/boost/gil/extension/numeric/kernel.hpp
  test/extension/numeric/Jamfile
  test/extension/numeric/kernel.cpp
  test/extension/numeric/kernel_1d_fixed_even_size_fail.cpp
Labels: cat/bug, ext/numeric

#324 Apply the rule of three in memory_based_2d_locator and iterator_from_2d
  include/boost/gil/image_view.hpp
  include/boost/gil/iterator_from_2d.hpp
  include/boost/gil/locator.hpp
Labels: cat/enhancement

#327 Removed unused documentation files
  doc/adobe_logo.gif
  doc/adobe_source.css
  doc/boost.png
  doc/build.sh
  doc/rst.css
  doc/shorten_file_name.sh
Labels: cat/documentation, cat/refactoring

#328 Add suppressive parentheses for function-like macro
  include/boost/gil/channel_algorithm.hpp
Labels: cat/annoyance

#326 Tidy up headers in gil/image_processing/ directory
  include/boost/gil/detail/math.hpp
  include/boost/gil/image_processing/numeric.hpp
  include/boost/gil/image_processing/scaling.hpp
Labels: cat/enhancement

#330 [gsoc2019] Add image_processing/scaling.hpp to boost/gil.hpp
  include/boost/gil.hpp
Labels: cat/bug

#329 [gsoc2019] Add color_spaces_are_compatible requirement as static_assert to threshold
  include/boost/gil/image_processing/threshold.hpp
  test/core/image_processing/Jamfile
  test/core/image_processing/threshold_color_spaces_not_compatible_fail.cpp
Labels: cat/enhancement

#321 Comparison operator changed to `>` from `>=` for threshold
  include/boost/gil/image_processing/threshold.hpp
Labels: cat/bug, core

#332 Fix error: RView identifier not found in planar_rgba_view
  include/boost/gil/concepts/pixel_locator.hpp
  include/boost/gil/rgba.hpp
  test/core/image_view/CMakeLists.txt
  test/core/image_view/Jamfile
  test/core/image_view/planar_rgba_view.cpp
Labels: cat/bug, test

#334 Add Image Processing section to Doxygen-based docs
  doc/doxyfile
  doc/reference.dox
Labels: cat/documentation

#335 Add first tests for convolve functions from Numeric extension
  test/core/pixel/test_fixture.hpp
  test/extension/numeric/CMakeLists.txt
  test/extension/numeric/Jamfile
  test/extension/numeric/convolve_2d.cpp
  test/extension/numeric/convolve_cols.cpp
  test/extension/numeric/convolve_rows.cpp
  test/extension/numeric/test_fixture.cpp
  test/extension/numeric/test_fixture.hpp
  test/unit_test.hpp
Labels: cat/enhancement, ext/numeric, test

#336 Compare float-pointing value to zero using <= operator
  include/boost/gil/image_processing/numeric.hpp
Labels: cat/enhancement

#322 New threshold tests added for multi channel views
  test/core/image_processing/threshold_binary.cpp
  test/core/image_processing/threshold_truncate.cpp
Labels: core, test

#338 Extract GIL-specific Boost.Test utilities from test/unit_test.hpp
  test/core/image_view/subimage_view.cpp
  test/core/pixel/test_fixture.cpp
  test/extension/dynamic_image/subimage_view.cpp
  test/extension/numeric/convolve_2d.cpp
  test/extension/numeric/convolve_cols.cpp
  test/extension/numeric/convolve_rows.cpp
  test/unit_test.hpp
  test/unit_test_utility.hpp
Labels: cat/refactoring, test

#314 [gsoc2019] Otsu threshold implemented
  include/boost/gil/image_processing/threshold.hpp
  test/core/image_processing/CMakeLists.txt
  test/core/image_processing/Jamfile
  test/core/image_processing/threshold_otsu.cpp
Labels: cat/feature, status/work-in-progress

#325 Split tutorial into separate documents for quickstart section
  doc/doxygen/before_after.dox
  doc/index.rst
  doc/installation.rst
  doc/naming.rst
  doc/tutorial/gradient.rst
  doc/tutorial/histogram.rst
  doc/tutorial/video.rst
Labels: cat/documentation, cat/enhancement

#346 Bump Sphinx version from 1.7.9 to 2.1
  .travis.yml
  doc/requirements.txt
Labels: cat/documentation

#347 `convolve` function added
  include/boost/gil/extension/numeric/convolve.hpp
Labels: cat/enhancement, ext/numeric

#349 Add test for convolve function from Numeric extension
  test/extension/numeric/convolve_2d.cpp
Labels: ext/numeric, test

#344 Assert user-specified positions within image or image_view are in range
  include/boost/gil/image.hpp
  include/boost/gil/image_view.hpp
Labels: cat/enhancement, cat/refactoring, core

#333 Update docs for threshold_binary function and enums
  include/boost/gil/image_processing/threshold.hpp
Labels: cat/documentation

#340 Add tests for extension/numeric/channel_numeric_operations.hpp
  include/boost/gil/extension/numeric/channel_numeric_operations.hpp
  test/core/channel/test_fixture.hpp
  test/extension/numeric/CMakeLists.txt
  test/extension/numeric/Jamfile
  test/extension/numeric/channel_numeric_operations.cpp
Labels: ext/numeric, test

#341 Add adaptive threshold algorithm using mean method
  example/adaptive_threshold.cpp
  example/test_adaptive.png
  include/boost/gil/image_processing/threshold.hpp
Labels: cat/feature, core

#355 Include <boost/gil.hpp> in examples
  example/adaptive_threshold.cpp
  example/convolution.cpp
  example/interleaved_ptr.cpp
  example/interleaved_ptr.hpp
  example/interleaved_ref.hpp
Labels: cat/annoyance

#357 Rename test/extension/numeric/convolve_2d.cpp to convolve.cpp
  test/extension/numeric/CMakeLists.txt
  test/extension/numeric/Jamfile
  test/extension/numeric/convolve.cpp
Labels: cat/refactoring

#358 Clarify what flavours of PNM formats can be read and written
  doc/io.rst
Labels: cat/documentation, ext/io

#339 Clarify correlation as cross-correlation and convolution as spatial convolution
  include/boost/gil/extension/numeric/algorithm.hpp
  include/boost/gil/extension/numeric/convolve.hpp
Labels: cat/documentation
