Repository boostorg/gil, pull requests merged in 2020-10, with the labels that each got.

#521 Fix typo in copyright headers.
  test/core/channel/scoped_channel_value.cpp
  test/test_utility_output_stream.hpp
Labels: cat/documentation

#522 Fix conversion of rgb to signed cmyk(boostorg#479)
  include/boost/gil/color_convert.hpp
  test/core/color/CMakeLists.txt
  test/core/color/Jamfile
  test/core/color/default_color_converter_rgb_to_cmyk.cpp
Labels: cat/bug

#520 Add image constructor from compatible view
  .gitignore
  include/boost/gil/image.hpp
  test/core/image/image.cpp
Labels: cat/feature
