Repository boostorg/gil, pull requests merged in 2020-04, with the labels that each got.

#473 Move math.hpp constants to detail namespace
  include/boost/gil/detail/math.hpp
  include/boost/gil/image_processing/numeric.hpp
  test/core/image_processing/sobel_scharr.cpp
Labels: cat/annoyance, cat/refactoring, core

#457 Add move semantics to image class
  include/boost/gil/image.hpp
  test/core/image/image.cpp
Labels: cat/enhancement

#476 Fix -Wsign-compare warning in uses of num_channels metafunction
  include/boost/gil/algorithm.hpp
  include/boost/gil/image.hpp
  test/legacy/image.cpp
Labels: cat/annoyance

#470 Fix invalid conversion from RGB8 to CMYK32 due to overflow
  include/boost/gil/color_convert.hpp
  test/core/pixel/CMakeLists.txt
  test/core/pixel/Jamfile
  test/core/pixel/color_convert_cmyk.cpp
Labels: cat/bug, core

#477 Fix image constructor from other image
  include/boost/gil/image.hpp
  test/core/image/image.cpp
  test/core/image/test_fixture.hpp
Labels: cat/bug

#481 Fix error plane_view_t is not a class or namespace name
  include/boost/gil/extension/toolbox/image_types/subchroma_image.hpp
Labels: cat/bug, ext/toolbox

#474 Replace Boost.Variant with Boost.Variant2
  .appveyor.yml
  .ci/get-boost.sh
  .travis.yml
  doc/design/dynamic_image.rst
  example/dynamic_image.cpp
  include/boost/gil/extension/dynamic_image/algorithm.hpp
  include/boost/gil/extension/dynamic_image/any_image.hpp
  include/boost/gil/extension/dynamic_image/any_image_view.hpp
  include/boost/gil/extension/dynamic_image/apply_operation.hpp
  include/boost/gil/extension/dynamic_image/image_view_factory.hpp
  include/boost/gil/extension/io/bmp/detail/read.hpp
  include/boost/gil/extension/io/bmp/detail/write.hpp
  include/boost/gil/extension/io/jpeg/detail/read.hpp
  include/boost/gil/extension/io/jpeg/detail/write.hpp
  include/boost/gil/extension/io/png/detail/read.hpp
  include/boost/gil/extension/io/png/detail/write.hpp
  include/boost/gil/extension/io/pnm/detail/read.hpp
  include/boost/gil/extension/io/pnm/detail/write.hpp
  include/boost/gil/extension/io/raw/detail/read.hpp
  include/boost/gil/extension/io/targa/detail/read.hpp
  include/boost/gil/extension/io/targa/detail/write.hpp
  include/boost/gil/extension/io/tiff/detail/read.hpp
  include/boost/gil/extension/io/tiff/detail/write.hpp
  include/boost/gil/extension/numeric/resample.hpp
  include/boost/gil/extension/toolbox/metafunctions/get_pixel_type.hpp
  include/boost/gil/io/dynamic_io_new.hpp
  include/boost/gil/io/read_image.hpp
  include/boost/gil/io/write_view.hpp
  test/extension/dynamic_image/test_fixture.hpp
  test/legacy/image.cpp
Labels: cat/enhancement

#487 Fix interleaved_view factory using point<std::ptrdiff_t> for dimension
  include/boost/gil/image_view_factory.hpp
Labels: cat/annoyance, core

#486 Add initializing image constructor
  include/boost/gil/extension/dynamic_image/any_image.hpp
  test/extension/dynamic_image/CMakeLists.txt
  test/extension/dynamic_image/Jamfile
  test/extension/dynamic_image/any_image.cpp
Labels: cat/enhancement, ext/dynamic_image

#490 added missing const& in extend_boundary parameters
  include/boost/gil/extension/numeric/algorithm.hpp
Labels: cat/enhancement

#489 Implemented mechanism to reverse kernel_2d
  include/boost/gil/extension/numeric/kernel.hpp
  test/extension/numeric/kernel.cpp
Labels: cat/enhancement, ext/numeric
