Repository boostorg/gil, pull requests merged in 2021-01, with the labels that each got.

#532 Add codecov coverage
  .ci/coverage.sh
  .travis.yml
Labels: test

#537 build: Switch conan packages from bincrafters to conan.io
  conanfile.txt
Labels: config/cmake

#527 Add inverse function for affine matrix3x2
  include/boost/gil/extension/numeric/affine.hpp
  test/extension/numeric/matrix3x2.cpp
Labels: cat/feature, ext/numeric

#542 Fix default ctor of homogeneous_color_base for reference pixel elements
  include/boost/gil/color_base.hpp
  test/core/pixel/test_fixture.hpp
Labels: cat/bug

#500 Add Perona–Malik anisotropic diffusion algorithm
  example/Jamfile
  example/anisotropic_diffusion.cpp
  include/boost/gil/image_processing/diffusion.hpp
  test/core/image_processing/CMakeLists.txt
  test/core/image_processing/Jamfile
  test/core/image_processing/anisotropic_diffusion.cpp
  test/core/test_fixture.hpp
Labels: cat/feature, google-summer-of-code

#499 Add histogram class and related functionality
  example/Jamfile
  example/histogram.cpp
  example/tutorial_histogram.cpp
  include/boost/gil.hpp
  include/boost/gil/extension/histogram/std.hpp
  include/boost/gil/histogram.hpp
  test/core/CMakeLists.txt
  test/core/Jamfile
  test/core/histogram/CMakeLists.txt
  test/core/histogram/Jamfile
  test/core/histogram/access.cpp
  test/core/histogram/constructor.cpp
  test/core/histogram/cumulative.cpp
  test/core/histogram/dimension.cpp
  test/core/histogram/fill.cpp
  test/core/histogram/hash_tuple.cpp
  test/core/histogram/helpers.cpp
  test/core/histogram/is_compatible.cpp
  test/core/histogram/key.cpp
  test/core/histogram/sub_histogram.cpp
  test/core/histogram/utilities.cpp
  test/extension/CMakeLists.txt
  test/extension/Jamfile
  test/extension/histogram/CMakeLists.txt
  test/extension/histogram/Jamfile
  test/extension/histogram/histogram.cpp
Labels: cat/feature, google-summer-of-code

#514 Add histogram equalization feature
  doc/image_processing/contrast_enhancement/barbara.jpg
  doc/image_processing/contrast_enhancement/church.jpg
  doc/image_processing/contrast_enhancement/he_chart.png
  doc/image_processing/contrast_enhancement/histogram_equalization.rst
  example/histogram_equalization.cpp
  include/boost/gil/image_processing/histogram_equalization.hpp
  test/core/image_processing/histogram_equalization.cpp
Labels: cat/feature, google-summer-of-code

#515 Add histogram matching algorithm
  doc/image_processing/contrast_enhancement/histogram_matching.rst
  doc/image_processing/contrast_enhancement/matching.jpg
  doc/image_processing/contrast_enhancement/matching_out.jpg
  example/histogram_matching.cpp
  include/boost/gil/image_processing/histogram_matching.hpp
  test/core/image_processing/histogram_matching.cpp
Labels: cat/feature, google-summer-of-code

#506 Implement hstack and vstack
  example/harris.cpp
  example/hvstack.hpp
Labels: cat/feature, google-summer-of-code

#516 Add adaptive histogram equalization algorithm
  example/adaptive_he.cpp
  include/boost/gil/image_processing/adaptive_histogram_equalization.hpp
  test/core/image_processing/adaptive_he.cpp
Labels: cat/feature, google-summer-of-code

#512 Add implementation of Hough transforms
  example/hough_transform_circle.cpp
  example/hough_transform_line.cpp
  example/rasterizer_circle.cpp
  example/rasterizer_line.cpp
  include/boost/gil.hpp
  include/boost/gil/image_processing/hough_parameter.hpp
  include/boost/gil/image_processing/hough_transform.hpp
  include/boost/gil/rasterization/circle.hpp
  include/boost/gil/rasterization/line.hpp
  test/core/CMakeLists.txt
  test/core/Jamfile
  test/core/image_processing/CMakeLists.txt
  test/core/image_processing/Jamfile
  test/core/image_processing/hough_circle_transform.cpp
  test/core/image_processing/hough_line_transform.cpp
  test/core/image_processing/hough_parameter.cpp
  test/core/rasterization/CMakeLists.txt
  test/core/rasterization/Jamfile
  test/core/rasterization/circle.cpp
  test/core/rasterization/line.cpp
Labels: cat/feature, core, google-summer-of-code

#552 Support constructing a planar image from interleaved image
  include/boost/gil/algorithm.hpp
  test/core/image/image.cpp
Labels: cat/bug, cat/enhancement
