Repository boostorg/gil, pull requests merged in 2021-02, with the labels that each got.

#545 Fixed most of the warnings in the examples and many of the boost build process
  example/hessian.cpp
  example/mandelbrot.cpp
  include/boost/gil/channel_algorithm.hpp
  include/boost/gil/color_base.hpp
  include/boost/gil/color_convert.hpp
  include/boost/gil/image_processing/harris.hpp
  include/boost/gil/image_processing/hessian.hpp
  include/boost/gil/image_processing/numeric.hpp
Labels: cat/annoyance

#556 Fix warning: returning reference to local temporary object
  include/boost/gil/extension/toolbox/image_types/subchroma_image.hpp
Labels: cat/bug, ext/toolbox

#557 Remove <cxxflags> and other cruft from Jamfile
  test/Jamfile
Labels: cat/annoyance, config/boost-build

#559 Review and update includes in boost/gil.hpp
  include/boost/gil.hpp
Labels: cat/annoyance

#560 Fix sphinx installation link in docs readme
  doc/README.md
Labels: cat/documentation

#541 Added all standard morphological transformations
  example/Jamfile
  example/morphology.cpp
  example/morphology_original.png
  include/boost/gil.hpp
  include/boost/gil/image_processing/morphology.hpp
  test/core/image_processing/CMakeLists.txt
  test/core/image_processing/Jamfile
  test/core/image_processing/morphology.cpp
Labels: cat/feature, core
