Repository boostorg/gil, pull requests merged in 2022-04, with the labels that each got.

#627 #605 Removed deprecated.hpp
  include/boost/gil.hpp
  include/boost/gil/deprecated.hpp
Labels: core

#650 fix: is_equal_to_sixteen in PNG I/O was less-than test
  include/boost/gil/extension/io/png/detail/write.hpp
Labels: cat/bug, ext/io

#653 refactor: Renamed io/dynamic_io_new.hpp to io/detail/dynamic.hpp
  include/boost/gil/extension/io/bmp/detail/read.hpp
  include/boost/gil/extension/io/bmp/detail/write.hpp
  include/boost/gil/extension/io/jpeg/detail/read.hpp
  include/boost/gil/extension/io/jpeg/detail/write.hpp
  include/boost/gil/extension/io/png/detail/read.hpp
  include/boost/gil/extension/io/png/detail/write.hpp
  include/boost/gil/extension/io/pnm/detail/read.hpp
  include/boost/gil/extension/io/pnm/detail/write.hpp
  include/boost/gil/extension/io/raw/detail/read.hpp
  include/boost/gil/extension/io/targa/detail/read.hpp
  include/boost/gil/extension/io/targa/detail/write.hpp
  include/boost/gil/extension/io/tiff/detail/read.hpp
  include/boost/gil/extension/io/tiff/detail/write.hpp
  include/boost/gil/io/detail/dynamic.hpp
Labels: cat/refactoring

#655 unified naming for pixel and channel operations
  include/boost/gil/pixel_numeric_operations.hpp
  test/core/pixel/pixel_numeric_operations.cpp
  test/core/pixel/pixel_numeric_operations_float.cpp
Labels: cat/refactoring

#648 feat: Added for_each_pixel overload for any_image
  include/boost/gil/extension/dynamic_image/algorithm.hpp
  test/extension/dynamic_image/Jamfile
  test/extension/dynamic_image/algorithm/Jamfile
  test/extension/dynamic_image/algorithm/for_each_pixel.cpp
Labels: cat/enhancement
