Repository boostorg/gil, pull requests merged in 2022-05, with the labels that each got.

#666 chore: Remove unused variable in diffusion.hpp
  include/boost/gil/image_processing/diffusion.hpp
Labels: core

#671 Fixed io extension build error
  include/boost/gil/extension/io/bmp/detail/write.hpp
  include/boost/gil/extension/io/jpeg/detail/write.hpp
  include/boost/gil/extension/io/png/detail/write.hpp
  include/boost/gil/extension/io/pnm/detail/write.hpp
  include/boost/gil/extension/io/targa/detail/write.hpp
  include/boost/gil/extension/io/tiff/detail/write.hpp
Labels: cat/bug, ext/io

#670 docs: Add partial release notes for Boost 1.80
  RELEASES.md
Labels: cat/documentation

#672 docs: Add remaining part of release notes for Boost 1.80
  RELEASES.md
Labels: cat/documentation

#654 fix: re-allow devicen_t with two color components
  include/boost/gil/device_n.hpp
Labels: core

#674 docs: add release notes for issue #654
  RELEASES.md
Labels: cat/documentation

#677 docs!: announce switch from C++11 to C++14 with Boost 1.80
  RELEASES.md
Labels: cat/documentation

#679 refactor: Make packed_pixel trivially copyable and assignable
  include/boost/gil/packed_pixel.hpp
Labels: cat/enhancement, core
