Repository boostorg/gil, pull requests merged in 2024-05, with the labels that each got.

#743 Guard boost::filesystem usage
  CMakeLists.txt
Labels: cat/feature, config/cmake

#746 fix wrong buffer size in path string conversion functions
  include/boost/gil/io/path_spec.hpp
Labels: cat/bug

#747 feat: add tell() and error() functions to istream + ostream devices
  include/boost/gil/io/device.hpp
Labels: cat/enhancement, cat/feature
